import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fbff',
    paddingTop: 25,
  },
  containerDark: {
    flex: 1,
    backgroundColor: '#0d1b2a',
    paddingTop: 25,
  },
  ToggleBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomColor: '#9b8d8d',
    borderBottomWidth: 0.5,
    alignItems: 'center',
    backgroundColor: 'purple',
    marginEnd: 5,
    marginStart: 5,
    borderRadius: 20
  },
  ToggleBarDark: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomColor: '#9b8d8d',
    borderBottomWidth: 0.5,
    alignItems: 'center',
    backgroundColor: '#1e293b',
    marginEnd: 5,
    marginStart: 5,
    borderRadius: 20
  },
  ToggleText: { fontSize: 20, color: '#011642' },
  ToggleTextDark: { fontSize: 20, color: '#ffffff' },
  navButton: { flexDirection: 'column', alignItems: 'center',  },
  navButtonDark: { flexDirection: 'column', alignItems: 'center', color: '#4e2e2e' },
  navSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 40,
    backgroundColor: 'purple',
    marginHorizontal: 20,
    padding: 10,
    borderRadius: 40,
  },
  navSectionDark: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 40,
    backgroundColor: '#1e293b',
    marginHorizontal: 20,
    padding: 10,
    borderRadius: 40,
  },
  MiddleBody: { flex: 1 },
  bodyText: { fontSize: 16, color: '#011642' },
  bodyTextDark: { fontSize: 16, color: '#ffffff' },
  headingText: { fontSize: 24, fontWeight: 'bold', color: '#011642' },
  headingTextDark: { fontSize: 24, fontWeight: 'bold', color: '#ffffff' },
  avatar: { width: 120, height: 120, borderRadius: 60, marginBottom: 15 },
  profileName: { fontSize: 24, fontWeight: 'bold', color: '#011642', marginBottom: 5 },
  profileNameDark: { fontSize: 24, fontWeight: 'bold', color: '#ffffff', marginBottom: 5 },
  profileBio: { fontSize: 16, color: '#555', marginBottom: 15, textAlign: 'center' },
  profileBioDark: { fontSize: 16, color: '#ccc', marginBottom: 15, textAlign: 'center' },
  contactItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  contactText: { fontSize: 16, color: '#011642' },
  contactTextDark: { fontSize: 16, color: '#ffffff' },
});
